# Generated by Django 4.1.7 on 2023-04-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverimage',
            name='id_article',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='static/avatars/'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
        migrations.DeleteModel(
            name='CoverImage',
        ),
    ]
