# Generated by Django 4.1.7 on 2023-04-02 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
