# Generated by Django 4.1.7 on 2023-04-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_alter_user_date_of_birth_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
